---
# tasks file for send_logs
- name: Send logs to S3
  block:
    - name: Install the latest version of Apache # sudo yum install httpd
      yum:
        name: httpd
        state: latest
      # ansible localhost -m yum - a "name=httpd state=latest"

    - name: Start httpd if not started # sudo systemctl start/enable httpd
      service:
        name: httpd
        state: started
        enabled: true

    - name: Romove index file, if created # /var/ww/html/index.html
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Add index file # /var/ww/html/index.html
      file:
        path: /var/www/html/index.html
        state: touch

    - name: Add line in index.html file
      lineinfile:
        path: /var/www/html/index.html
        line: <h1> This is the {{companyName}}.<h1>

    - name: Add line in index.html file
      lineinfile:
        path: /var/www/html/index.html
        line: <h1> {{line}}... <h1>

    - name: Make sure python and pip are installed
      yum:
        name:
          - python
          - pip
    
    - name: Make sure boto, boto3 and botocore are installed
      pip:
        name: "{{ item }}"
      loop: 
        - boto
        - boto3
        - botocore

    - name: Save folder name
      set_fact:
        folder_name: "{{ hostvars[inventory_hostname]['public_dns_name']}}"

    #- debug: msg="{{ folder_name}}"

    - name: Create folder for instance in S3
      aws_s3: 
        bucket: kmackey-logs
        mode: create
        object: "{{ folder_name }}"

    - name: Deposit error log in S3 folder
      aws_s3: 
        bucket: kmackey-logs
        mode: put
        object: "{{ folder_name }}/error_log"
        src: "/etc/httpd/logs/error_log"