---
# tasks file for second_role
- name: Add several users to a group
  user:
    name: "{{item}}"
    state: present
    group: "wheel"
  loop:
    - dog
    - giraffe
    - fish
    - bird
    - elephant
    - bear